### PR TITLE
Draft: Network Rule

### PR DESCRIPTION
**Pull request by benjohnde**
Network Rule to check for connectivity!

### CODE REVIEW

**Comment by benjohnde** [comment]
@canonall currently, there is no real 'cool' way to do so. I will look into a potential solution. Are you looking for the current state (and may fetch that one periodically) or do you need rather a state observer?

**Comment by benjohnde** [comment]
My favourite way to do so would be to implement the [NWPathMonitor](https://developer.apple.com/documentation/network/nwpathmonitor) for iOS. It's available since iOS 12 and would fit in our use case, cf. [example](https://stackoverflow.com/questions/1083701/how-can-i-check-for-an-active-internet-connection-on-ios-or-macos/64444348#64444348).

The main problem here is that this one is not available in ObjC as new frameworks will be written in Swift only. As there is still a missing Kotlin/Native Interoperability with Swift, [you cannot use the framework easily](https://slack-chats.kotlinlang.org/c/multiplatform/92). We could implement an own framework in ObjC which basically represents glue code for accessing Swift frameworks. But I wouldn't do so.

**Comment by gaebel** [comment]
I'd just observe the network state in the queue class. Then check if internet is available before running a job (suspend until internet) and pass the current state (cellular, wifi, ...) into the job.run function for the network rule (either store the state in the job context or pass it into willRun. You have to lift the withTimeout block out of the job class into the queue.

**Comment by benjohnde** [comment]
@canonall ah there is a way to use NWPathMonitor, although it looks a bit ugly, that one should work:

```kotlin
package com.liftric.job.queue

import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.receiveAsFlow
import platform.Network.*
import platform.darwin.DISPATCH_QUEUE_PRIORITY_DEFAULT
import platform.darwin.dispatch_queue_attr_make_with_qos_class
import platform.darwin.dispatch_queue_create
import platform.posix.QOS_CLASS_UTILITY

enum class NetworkConnectionType {
    Wifi, Cellular, Unsatisfied
}

class NWPathNetworkManager {
    private val networkChannel = Channel<NetworkConnectionType>(Channel.UNLIMITED)
    val network: Flow<NetworkConnectionType> = networkChannel.receiveAsFlow()

    private val networkMonitor = object : nw_path_monitor_update_handler_t {
        override fun invoke(network: nw_path_t) {
            checkReachability(network)
        }
    }
    private val nwPathMonitor: nw_path_monitor_t = nw_path_monitor_create().apply {
        val queue = dispatch_queue_create(
            "com.liftric.job.queue",
            dispatch_queue_attr_make_with_qos_class(
                null,
                QOS_CLASS_UTILITY,
                DISPATCH_QUEUE_PRIORITY_DEFAULT
            )
        )
        nw_path_monitor_set_queue(
            this,
            queue
        )
        nw_path_monitor_set_update_handler(this, networkMonitor)
    }

    fun startMonitoring() {
        nw_path_monitor_start(nwPathMonitor)
    }

    fun stopMonitoring() {
        nw_path_monitor_cancel(nwPathMonitor)
    }

    private fun checkReachability(network: nw_path_t) {
        when (nw_path_get_status(network)) {
            nw_path_status_satisfied -> {
                if (nw_path_uses_interface_type(network, nw_interface_type_wifi)) {
                    networkChannel.trySend(NetworkConnectionType.Wifi)
                } else if (nw_path_uses_interface_type(network, nw_interface_type_cellular)) {
                    networkChannel.trySend(NetworkConnectionType.Cellular)
                }
            }
            nw_path_status_unsatisfied -> {
                networkChannel.trySend(NetworkConnectionType.Unsatisfied)
            }
        }
    }
}
```

**Comment by benjohnde** [comment]
> I'd just observe the network state in the queue class. Then check if internet is available before running a job (suspend until internet) and pass the current state (cellular, wifi, ...) into the job.run function for the network rule (either store the state in the job context or pass it into willRun. You have to lift the withTimeout block out of the job class into the queue.

Check, @canonall feel free to create a new branch, based on main (guess that way it is easier) and cherry-pick your changes. Then you can use the snippet above (although that limits the library to iOS 12 which does not bother me at all) and retrieve the network state for iOS.

**Pull request closed without merging**
